name: Debug Master CI & PR

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build_apk_aab:
    if: startsWith(github.head_ref, 'release/') == false
    name: Build debug artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test
        run: |
          ./gradlew test
          ./gradlew assembleDebug

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/*

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
