name: Debug Master CI & PR

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build_apk_aab:
    if: startsWith(github.head_ref, 'release/') == false
    name: Build debug artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Detekt, Lint, Test, build
        run: |
          ./gradlew checkAll
          ./gradlew lintDebug
          ./gradlew test
          ./gradlew assembleDebug

      - name: Upload Detekt results
        uses: actions/upload-artifact@v2
        with:
          name: detekt-results
          path: app/build/reports/detekt.html

      - name: Upload Lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: app/build/outputs/lint/lint.html

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests/testDebugUnitTest/*